### PR TITLE
Fix appveyor.

### LINKED ISSUE #22: Appveyor should build pull requests.
Appveyor should build pull requests.

### PR DESCRIPTION
**Pull request by Highlife1911**
Fixes #22

### CODE REVIEW

**Comment by lawben** [comment]
This now builds twice on appveyor. Is it possible to disable on of them (preferably the `/branch` one)?

**Comment by Highlife1911** [comment]
This is now build 5 times, i changed it and now it should only build 2 times.

**Comment by lawben** [comment]
It seems like if we take out the `branch master only` line, it build for each push on any branch, which will explode at some point... 
Also, why are we disabling MSVC 2015? Don't we want to support that?

**Comment by Highlife1911** [comment]
The multi build was caused by wrong configured webhooks. This is correct now.

We do not want to support MSVC 2015 anymore because it lacks some C++14 features we are needing, like C++14 constexpr.

**Pull request merged**
